'use client';

import React from 'react';
import { AIStoryCard } from '@/components/ai/AIStoryCard';

export default function AIStoryPage() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-1">
        <h1 className="text-2xl font-bold">AI Data Stories</h1>
        <p className="text-gray-500 text-sm">Deep insights generated by Anthropic Claude.</p>
      </div>

      <div className="max-w-3xl mx-auto">
        <AIStoryCard />
      </div>
    </div>
  );
}
